### ISSUE TITLE
Links not opening

### ISSUE THREAD

**Issue by michaelb87** [damoonrashidi/wdp#2]
Hi,
links aren't opening for me (Ubuntu 17.04). Can you explain, how the following line works?

https://github.com/damoonrashidi/wdp/blob/ddec59c34309b543d066d9628efd88ee448acea5/src/index.tsx#L52

Thanks

**Comment by damoonrashidi** [comment]
It spawns a child process that opens chrome to the URL of the selected list item. It's mostly because I was lazy that chrome is hardcoded. I can do a safer way of opening the user's default browser instead (if chrome is not available).

I can push a fix today. Thanks for providing OS.

**Comment by damoonrashidi** [comment]
Alright, v1.3.0 should fix this, please let me know if it doesn't.
